
package com.zh.interfaceManager.client.realname;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManageUserInfoWebServiceWSDelegate", targetNamespace = "http://ManageUserInfoWebServiceWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageUserInfoWebServiceWSDelegate {


    /**
     * 
     * @param phone
     * @param commonHeader
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityPhoneVerificationCode
     */
    @WebMethod(operationName = "ICT_GetPhoneVerificationCode")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_GetPhoneVerificationCode", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTGetPhoneVerificationCode")
    @ResponseWrapper(localName = "ICT_GetPhoneVerificationCodeResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTGetPhoneVerificationCodeResponse")
    public ResponseEntityPhoneVerificationCode ictGetPhoneVerificationCode(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "phone", targetNamespace = "")
        String phone);

    /**
     * 
     * @param commonHeader
     * @param registerUser
     * @param tranData
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityLogOutRegisterUser
     */
    @WebMethod(operationName = "ICT_LogOutUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_LogOutUser", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTLogOutUser")
    @ResponseWrapper(localName = "ICT_LogOutUserResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTLogOutUserResponse")
    public ResponseEntityLogOutRegisterUser ictLogOutUser(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "registerUser", targetNamespace = "")
        RegisterUser registerUser,
        @WebParam(name = "tranData", targetNamespace = "")
        String tranData);

    /**
     * 
     * @param idType
     * @param commonHeader
     * @param idNoName
     * @param idNumber
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityBlackList
     */
    @WebMethod(operationName = "ICT_QueryBlackList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_QueryBlackList", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryBlackList")
    @ResponseWrapper(localName = "ICT_QueryBlackListResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryBlackListResponse")
    public ResponseEntityBlackList ictQueryBlackList(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "id_type", targetNamespace = "")
        String idType,
        @WebParam(name = "id_number", targetNamespace = "")
        String idNumber,
        @WebParam(name = "id_no_name", targetNamespace = "")
        String idNoName);

    /**
     * 
     * @param phone
     * @param commonHeader
     * @param complaintIdNo
     * @param complaintIdType
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityRegisterUser
     */
    @WebMethod(operationName = "ICT_QueryBundlingMobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_QueryBundlingMobile", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryBundlingMobile")
    @ResponseWrapper(localName = "ICT_QueryBundlingMobileResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryBundlingMobileResponse")
    public ResponseEntityRegisterUser ictQueryBundlingMobile(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "complaint_id_type", targetNamespace = "")
        String complaintIdType,
        @WebParam(name = "complaint_id_no", targetNamespace = "")
        String complaintIdNo,
        @WebParam(name = "phone", targetNamespace = "")
        String phone);

    /**
     * 
     * @param commonHeader
     * @param registerUser
     * @param tranData
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityPassenger
     */
    @WebMethod(operationName = "ICT_QueryPassengerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_QueryPassengerInfo", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryPassengerInfo")
    @ResponseWrapper(localName = "ICT_QueryPassengerInfoResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryPassengerInfoResponse")
    public ResponseEntityPassenger ictQueryPassengerInfo(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "registerUser", targetNamespace = "")
        RegisterUser registerUser,
        @WebParam(name = "tranData", targetNamespace = "")
        String tranData);

    /**
     * 
     * @param commonHeader
     * @param registerUser
     * @param tranData
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityRegisterUser
     */
    @WebMethod(operationName = "ICT_QueryUserInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_QueryUserInfo", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryUserInfo")
    @ResponseWrapper(localName = "ICT_QueryUserInfoResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTQueryUserInfoResponse")
    public ResponseEntityRegisterUser ictQueryUserInfo(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "registerUser", targetNamespace = "")
        RegisterUser registerUser,
        @WebParam(name = "tranData", targetNamespace = "")
        String tranData);

    /**
     * 
     * @param idNo
     * @param idType
     * @param phone
     * @param commonHeader
     * @param registerUserName
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityReisterUser
     */
    @WebMethod(operationName = "ICT_SynchronizedUserByRegister")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_SynchronizedUserByRegister", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTSynchronizedUserByRegister")
    @ResponseWrapper(localName = "ICT_SynchronizedUserByRegisterResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTSynchronizedUserByRegisterResponse")
    public ResponseEntityReisterUser ictSynchronizedUserByRegister(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "id_type", targetNamespace = "")
        String idType,
        @WebParam(name = "id_no", targetNamespace = "")
        String idNo,
        @WebParam(name = "phone", targetNamespace = "")
        String phone,
        @WebParam(name = "register_user_name", targetNamespace = "")
        String registerUserName);

    /**
     * 
     * @param idNo
     * @param idType
     * @param phone
     * @param commonHeader
     * @param tranData
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityVerifyMobile
     */
    @WebMethod(operationName = "ICT_UnbundlMobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_UnbundlMobile", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTUnbundlMobile")
    @ResponseWrapper(localName = "ICT_UnbundlMobileResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTUnbundlMobileResponse")
    public ResponseEntityVerifyMobile ictUnbundlMobile(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "id_type", targetNamespace = "")
        String idType,
        @WebParam(name = "id_no", targetNamespace = "")
        String idNo,
        @WebParam(name = "phone", targetNamespace = "")
        String phone,
        @WebParam(name = "tranData", targetNamespace = "")
        String tranData);

    /**
     * 
     * @param idNo
     * @param idType
     * @param phone
     * @param commonHeader
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityVerifyMobile
     */
    @WebMethod(operationName = "ICT_UpdateMobileStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_UpdateMobileStatus", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTUpdateMobileStatus")
    @ResponseWrapper(localName = "ICT_UpdateMobileStatusResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTUpdateMobileStatusResponse")
    public ResponseEntityVerifyMobile ictUpdateMobileStatus(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "id_type", targetNamespace = "")
        String idType,
        @WebParam(name = "id_no", targetNamespace = "")
        String idNo,
        @WebParam(name = "phone", targetNamespace = "")
        String phone);

    /**
     * 
     * @param idNo
     * @param idType
     * @param registerIdNo
     * @param commonHeader
     * @param countryCode
     * @param realName
     * @param registerName
     * @return
     *     returns com.zh.interfaceManager.client.realname.ResponseEntityReisterUser
     */
    @WebMethod(operationName = "ICT_VerifyRegisterUserStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_VerifyRegisterUserStatus", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTVerifyRegisterUserStatus")
    @ResponseWrapper(localName = "ICT_VerifyRegisterUserStatusResponse", targetNamespace = "http://ManageUserInfoWebServiceWS", className = "com.zh.interfaceManager.client.realname.ICTVerifyRegisterUserStatusResponse")
    public ResponseEntityReisterUser ictVerifyRegisterUserStatus(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "register_id_no", targetNamespace = "")
        String registerIdNo,
        @WebParam(name = "register_name", targetNamespace = "")
        String registerName,
        @WebParam(name = "real_name", targetNamespace = "")
        String realName,
        @WebParam(name = "id_type", targetNamespace = "")
        String idType,
        @WebParam(name = "id_no", targetNamespace = "")
        String idNo,
        @WebParam(name = "country_code", targetNamespace = "")
        String countryCode);

}
