
package com.zh.interfaceManager.client.dpdd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TRSForCustomerSupportCenterServices2Delegate", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TRSForCustomerSupportCenterServices2Delegate {


    /**
     * 
     * @param iCTOrderInfoByUserRQ2
     * @return
     *     returns com.zh.interfaceManager.client.dpdd.IctOrderInfoByUserRS2
     */
    @WebMethod(operationName = "ICT_OrderInfoByUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_OrderInfoByUser", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.dpdd.ICTOrderInfoByUser")
    @ResponseWrapper(localName = "ICT_OrderInfoByUserResponse", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.dpdd.ICTOrderInfoByUserResponse")
    public IctOrderInfoByUserRS2 ictOrderInfoByUser(
        @WebParam(name = "iCT_OrderInfoByUserRQ2", targetNamespace = "")
        IctOrderInfoByUserRQ2 iCTOrderInfoByUserRQ2);

    /**
     * 
     * @param commonHeader
     * @param insuranceNo
     * @param saleStartDate
     * @param insureIdType
     * @param sequenceNo
     * @param saleEndDate
     * @param loginName
     * @param insureIdNo
     * @return
     *     returns com.zh.interfaceManager.client.dpdd.IctInsuranceRRT
     */
    @WebMethod(operationName = "ICT_QueryAccidentInsurance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ICT_QueryAccidentInsurance", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.dpdd.ICTQueryAccidentInsurance")
    @ResponseWrapper(localName = "ICT_QueryAccidentInsuranceResponse", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.dpdd.ICTQueryAccidentInsuranceResponse")
    public IctInsuranceRRT ictQueryAccidentInsurance(
        @WebParam(name = "commonHeader", targetNamespace = "")
        CommonHeader commonHeader,
        @WebParam(name = "sale_start_date", targetNamespace = "")
        String saleStartDate,
        @WebParam(name = "sale_end_date", targetNamespace = "")
        String saleEndDate,
        @WebParam(name = "insure_id_type", targetNamespace = "")
        String insureIdType,
        @WebParam(name = "insure_id_no", targetNamespace = "")
        String insureIdNo,
        @WebParam(name = "insurance_no", targetNamespace = "")
        String insuranceNo,
        @WebParam(name = "sequence_no", targetNamespace = "")
        String sequenceNo,
        @WebParam(name = "login_name", targetNamespace = "")
        String loginName);

    /**
     * 
     * @param stationTelecode
     * @param trainDate
     * @param stationTrainCode
     * @return
     *     returns com.zh.interfaceManager.client.dpdd.IctCheckTicketPlatForm
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCheckTicketInfo", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.dpdd.QueryCheckTicketInfo")
    @ResponseWrapper(localName = "queryCheckTicketInfoResponse", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.dpdd.QueryCheckTicketInfoResponse")
    public IctCheckTicketPlatForm queryCheckTicketInfo(
        @WebParam(name = "train_date", targetNamespace = "")
        String trainDate,
        @WebParam(name = "station_train_code", targetNamespace = "")
        String stationTrainCode,
        @WebParam(name = "station_telecode", targetNamespace = "")
        String stationTelecode);

}
