
package com.zh.interfaceManager.client.jpk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TRSForCustomerSupportCenterServices2Delegate", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TRSForCustomerSupportCenterServices2Delegate {


   

    /**
     * 
     * @param stationTelecode
     * @param trainDate
     * @param stationTrainCode
     * @return
     *     returns com.zh.interfaceManager.client.dpdd.IctCheckTicketPlatForm
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCheckTicketInfo", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.jpk.QueryCheckTicketInfo")
    @ResponseWrapper(localName = "queryCheckTicketInfoResponse", targetNamespace = "http://TRSForCustomerSupportCenterServices2Service", className = "com.zh.interfaceManager.client.jpk.QueryCheckTicketInfoResponse")
    public IctCheckTicketPlatForm queryCheckTicketInfo(
        @WebParam(name = "train_date", targetNamespace = "")
        String trainDate,
        @WebParam(name = "station_train_code", targetNamespace = "")
        String stationTrainCode,
        @WebParam(name = "station_telecode", targetNamespace = "")
        String stationTelecode);

}
