
package com.zh.interfaceManager.client.postvm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "queryPOSTVM", targetNamespace = "http://ws.otsweb.ict.cars.com/queryPOSTVMServiceEndPoint", wsdlLocation = "file:/D:/workspace/middleware/src/ictPOSTVMQueryServiceEndPoint.wsdl")
public class QueryPOSTVM_Service
    extends Service
{

    private final static URL QUERYPOSTVM_WSDL_LOCATION;
    private final static WebServiceException QUERYPOSTVM_EXCEPTION;
    private final static QName QUERYPOSTVM_QNAME = new QName("http://ws.otsweb.ict.cars.com/queryPOSTVMServiceEndPoint", "queryPOSTVM");

    static {
        URL url = null;
        WebServiceException e = null;
        String path=Thread.currentThread().getContextClassLoader().getResource("ictPOSTVMQueryServiceEndPoint.wsdl").toString();
        try {
        	URL baseUrl;
        	baseUrl=com.zh.interfaceManager.client.postvm.QueryPOSTVM_Service.class.getResource(".");
        	url=new URL(baseUrl,path);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYPOSTVM_WSDL_LOCATION = url;
        QUERYPOSTVM_EXCEPTION = e;
    }

    public QueryPOSTVM_Service() {
        super(__getWsdlLocation(), QUERYPOSTVM_QNAME);
    }

    public QueryPOSTVM_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYPOSTVM_QNAME, features);
    }

    public QueryPOSTVM_Service(URL wsdlLocation) {
        super(wsdlLocation, QUERYPOSTVM_QNAME);
    }

    public QueryPOSTVM_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYPOSTVM_QNAME, features);
    }

    public QueryPOSTVM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryPOSTVM_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICTPOSTVMQueryServiceEndPoint
     */
    @WebEndpoint(name = "ICTPOSTVMQueryServiceEndPointPort")
    public ICTPOSTVMQueryServiceEndPoint getICTPOSTVMQueryServiceEndPointPort() {
        return super.getPort(new QName("http://ws.otsweb.ict.cars.com/queryPOSTVMServiceEndPoint", "ICTPOSTVMQueryServiceEndPointPort"), ICTPOSTVMQueryServiceEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICTPOSTVMQueryServiceEndPoint
     */
    @WebEndpoint(name = "ICTPOSTVMQueryServiceEndPointPort")
    public ICTPOSTVMQueryServiceEndPoint getICTPOSTVMQueryServiceEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.otsweb.ict.cars.com/queryPOSTVMServiceEndPoint", "ICTPOSTVMQueryServiceEndPointPort"), ICTPOSTVMQueryServiceEndPoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYPOSTVM_EXCEPTION!= null) {
            throw QUERYPOSTVM_EXCEPTION;
        }
        return QUERYPOSTVM_WSDL_LOCATION;
    }

}
